SKILL_ALIASES = {
    "javascript": ["javascript", "js", "ecmascript"],
    "typescript": ["typescript"],
    "react": ["react", "react.js", "reactjs"],
    "node.js": ["node", "node.js", "nodejs"],
    "express": ["express", "express.js", "expressjs"],
    "mongodb": ["mongodb", "mongo db", "mongoose"],
    "rest api": ["rest api", "restful", "api development"],
    "html": ["html", "html5"],
    "css": ["css", "css3", "tailwind", "bootstrap"],
    "git": ["git", "github", "gitlab"],
    "docker": ["docker", "containerization"],
    "aws": ["aws", "amazon web services"],
    "python": ["python"],
    "fastapi": ["fastapi"],
    "django": ["django"],
    "flask": ["flask"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "machine learning": ["machine learning", "ml algorithms"],
    "deep learning": ["deep learning", "neural network", "tensorflow", "pytorch"],
    "nlp": ["natural language processing", "nlp"],
    "sql": ["sql", "mysql", "postgresql", "postgres"],
    "java": ["java"],
    "spring boot": ["spring boot", "springboot"],
    "c++": ["c++", "cpp"],
    "data visualization": ["data visualization", "tableau", "power bi", "matplotlib", "seaborn"],
    "excel": ["microsoft excel", "ms excel", "excel"],
    "figma": ["figma"],
    "ui/ux": ["ui/ux", "user experience", "user interface design"],
    "testing": ["unit testing", "integration testing", "jest", "pytest"],
}

ROLE_PROFILES = {
    "MERN Stack Developer": "javascript react node.js express mongodb html css rest api git full stack web development",
    "Frontend Developer": "javascript typescript react html css responsive ui accessibility testing figma",
    "Backend Developer": "node.js express python django fastapi sql mongodb rest api security docker testing",
    "Data Scientist": "python pandas numpy scikit-learn machine learning statistics sql data visualization nlp",
    "Machine Learning Engineer": "python machine learning deep learning scikit-learn tensorflow pytorch nlp docker api",
    "Java Developer": "java spring boot sql rest api git testing microservices docker",
    "Data Analyst": "sql excel python pandas data visualization tableau power bi statistics",
    "UI/UX Designer": "figma ui/ux user research prototyping wireframes accessibility design systems",
}

